version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18  # Adjust to the Node.js version needed for compatibility with your project
    commands:
      - echo Installing root-level dependencies, if any...
      - npm install  # Installs any dependencies at the root level (if required)

  pre_build:
    commands:
      - echo Changing directory to 'my-app' for app-specific dependencies...
      - cd my-app  # Move to the app directory if it's nested within the project structure
      - echo Installing NPM dependencies for the React app...
      - npm install  # Installs dependencies specifically for the React app in 'my-app' folder

  build:
    commands:
      - echo Building the React application...
      - npm run build  # Executes the build command for the React app, outputting to 'my-app/build'

artifacts:
  files:
    - '**/*'  # Includes all files from the 'build' directory in the artifacts
  base-directory: 'my-app/build'  # Specify the directory containing the final build output
  # discard-paths: yes  # Uncomment if you want only the files inside the build folder in the artifacts
